git:
  depth: 3

language: node_js

os:
  - linux
  - osx

node_js:
  - "node"
  - "6"
  - "5"
  - "4"

install:
  - travis_wait npm install

before_script:
  - node --version
  - npm --version
  - npm run lint
  - npm run test

script:
  - npm run build
